### ISSUE TITLE
Feedback on 01.Rmd for Milestone 1

### ISSUE THREAD

**Issue by andrewlarimer** [w201rdada/portfolio-jakemiller649#1]
Hi Jake,

Very cool idea. Here's what I'm taking away:

> A lot of food (particularly fruits & vegetables) go to waste, while a lot of people still go hungry. Efforts to connect that food to the hungry are underway, but they could be enhanced by data science to allow charitable organizations distributing food to the needy to better predict upcoming availability of donated food.

One thing I really liked was how you clearly specified that the onus of measuring and verifying the food would be done by the charitable organization, as that question was definitely popping up in my head right before I arrived at that statement, so that was well-timed.

Also great job on already having some sources in there.

One piece that I feel like could be strengthened a bit is clarifying the benefits of the predictions a little bit more. I understood the sentence about lessening their own potential food waste by presumably not opening a lot of nonperishable cans right before they get a big food donation, but I wasn't sure that I bought that that was necessarily a big problem happening now. I didn't quite understand what you meant by the previous sentence: "In turn, they will be able to more proactively address new hunger needs of their communities as they arise." So I would just love to either have something backing up the fact that waste within a shelter/food charity itself is indeed a problem, or some other proof of the real-world benefits to these organizations.

Overall, I felt like it was very clear, obviously addresses a problem, and I can easily imagine this being developed into a Capstone project.

**Comment by jakemiller649** [comment]
Deleted some dubious benefits and added to existing ones. Thanks for feedback!
