### ISSUE TITLE
feedback for milestone 1

### ISSUE THREAD

**Issue by jcrosok** [w201rdada/portfolio-jakemiller649#2]
I think the gist of your idea is that you want to create a model that will predict the volume, timing and type of food donations charitable organizations can expect to receive throughout the year which has an additional benefit of limiting food waste. 

Your introduction is really strong and clearly states the two problems you are seeking to address with this project.

I really like how you clarify that the charitable orgs will be responsible for collecting data, but I wonder how equipped they are to do this in practice. Also, how detailed will the data they collect be required to be? Does the data collection go on indefinitely or just for the initial year or two? I think it would help to get into the logistics here a bit more, because if collecting data isn't easy people will make mistakes or not do it at all. 

Once there is more clarity around exactly what data is going to be collected and how, I would love to see more information on the model itself. What specifically will be the output of the model and how is it actionable for the charities? 

This definitely complicates your project so take this with a grain of salt - something that popped up in my head is that since all these charities are putting their info into the same system, I wonder if the model could suggest that restaurants redirect their donations to charities that need what they're donating more or potentially that charities could trade what they're receiving in order to balance out their resources if one place ends up with too much grains while the other has too much produce.

**Comment by jakemiller649** [comment]
- Tried to add beef to both data collection and presentation
- Re: your last point, I did think about that and perhaps it is outside the scope of my idea (at least for now). In the course of my research, I came across something similar in the UK. 


Thanks for the help
