### ISSUE TITLE
Feedback for Milestone 1

### ISSUE THREAD

**Issue by tweismann** [w201rdada/portfolio-jakemiller649#3]
Applying data science to food waste and donation could not only improve the utilization rate for discarded food, but potentially reduce the aggregate need for producing food overall by realizing efficiencies.  This idea is exciting and far reaching.  The gist of your idea is to deploy a pre-owned food supply prediction model to help charitable organizations plan for the immediate future.

One major strength of the model is that it may be a straightforward application with minimal nuance, relative to something like behavioral science.  Food supplies are somewhat constant, as is food consumption behavior, so it follows that predicting food waste or food donations may be relatively uncomplicated.  Drawing from the same principle, it might also relatively straightforward to predict consumption by food banks as well.  Predicting both supply and demand for food banks and other charitable food organizations could help improve aggregate efficiency in using donated food to feed more people.  

One challenge is operator ability to understand and effectively use the predictions to improve service outcomes.  The saying 'the best tool is the one that gets used' comes to mind here.  UI/UX simplicity may be a key success factor to consider. 

The idea is loaded with potential and I'm excited to see how it develops!

**Comment by jakemiller649** [comment]
Good comment -- UI/UX isn't something I had given much consideration to as I was developing the idea, but another person also had a similar comment. Definitely pushed me in the right direction. Thanks!
